bash:
  paths:
    ~/.profile: Tools/Shell/.profile
    ~/.bash_profile: Tools/Shell/.bash_profile
    ~/.bashrc: Tools/Shell/.bashrc
zsh:
  paths:
    ~/.zshenv: Tools/Shell/.zshenv
    ~/.zprofile: Tools/Shell/.zprofile
    ~/.zshrc: Tools/Shell/.zshrc
    ~/.alias: Tools/Shell/.alias
    ~/.env: Tools/Shell/.env
fish:
  paths:
    ~/.config/fish/config.fish: Tools/Shell/config.fish
vim:
  paths:
    ~/.vimrc: Tools/Vim/.vimrc
nvim:
  paths:
    ~/.config/nvim/init.lua: Tools/Neovim/init.lua
    ~/.config/nvim/lua/: Tools/Neovim/lua/.. 
helix:
  paths:
    ~/.config/helix/config.toml: Tools/Helix/config.toml
    ~/.config/helix/languages.toml: Tools/Helix/languages.toml
emacs:
  paths:
    ~/.emacs.d/init.el: Tools/Emacs/init.el
vscode:
  paths:
    "~/Library/Application Support/Code/User/settings.json": Tools/VSCode/settings.json
    "~/Library/Application Support/Code/User/keybindings.json": Tools/VSCode/keybindings.json
rime:
  paths:
    ~/Library/Rime/.: App/Rime/
sogou:
  paths:
    "~/Library/Application Support/Sogou/InputMethod/SogouPY/symbolSubsitute.plist": App/SogouInput/symbolSubsitute.plist
espanso:
iterm2:
  paths:
    "~/Library/Preferences/com.googlecode.iterm2.plist": macOS/iTerm/com.googlecode.iterm2.plist
    "~/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json": macOS/iTerm/Profiles.json
alacritty:
  paths:
    ~/.config/alacritty/alacritty.yml: Tools/Alacritty/alacritty.yml
kitty:
  paths:
    ~/.config/kitty/kitty.conf: Tools/Kitty/kitty.conf
tmux:
  paths:
    ~/.tmux.conf: Tools/Tmux/.tmux.conf
git:
  paths:
    ~/.gitconfig: Tools/Git/.gitconfig
nodejs:
  paths:
    ~/.npmrc: Dev/JavaScript/.npmrc
pip:
  paths:
    ~/.config/pip/pip.conf: Dev/Python/pip.conf
conda:
  paths:
    ~/.condarc: Dev/Python/.condarc
cargo:
  paths:
    ~/.cargo/config.toml: Dev/Rust/config.toml
sbt:
  paths:
    ~/.sbt/repositories: Dev/Scala/repositories
ansible:
docker:
podman:
kubernetes:
hammerspoon:
  paths:
    ~/.hammerspoon/init.lua: macOS/Hammerspoon/init.lua
sleepwatcher:
  paths:
    ~/.sleep: macOS/SleepWatcher/.sleep
    ~/.wakeup: macOS/SleepWatcher/.wakeup
mac-mouse-fix:
  paths:
    "~/Library/Application Support/com.nuebling.mac-mouse-fix/config.plist": macOS/Mac-Mouse-Fix/config.plist
obs:
