bash:
  files:
    ~/.profile: Dev/Shell/.profile
    ~/.bash_profile: Dev/Shell/.bash_profile
    ~/.bashrc: Dev/Shell/.bashrc
zsh:
  files:
    ~/.zshenv: Dev/Shell/.zshenv
    ~/.zprofile: Dev/Shell/.zprofile
    ~/.zshrc: Dev/Shell/.zshrc
    ~/.alias: Dev/Shell/.alias
    ~/.env: Dev/Shell/.env
fish:
  files:
    ~/.config/fish/config.fish: Dev/Shell/config.fish
vim:
  files:
    ~/.vimrc: App/Vim/.vimrc
emacs:
  files:
    ~/.emacs.d/init.el: App/Emacs/init.el
vscode:
  files:
    "~/Library/Application Support/Code/User/settings.json": App/VSCode/settings.json
    "~/Library/Application Support/Code/User/keybindings.json": App/VSCode/keybindings.json
rime:
  files:
    ~/Library/Rime/.: App/Rime/
espanso:
iterm2:
  files:
    "~/Library/Preferences/com.googlecode.iterm2.plist": macOS/iTerm/com.googlecode.iterm2.plist
    "~/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json": macOS/iTerm/Profiles.json
alacritty:
  files:
    ~/.config/alacritty/alacritty.yml: App/Alacritty/alacritty.yml
tmux:
  files:
    ~/.tmux.conf: App/Tmux/.tmux.conf
git:
  files:
    ~/.gitconfig: Dev/Git/.gitconfig
nodejs:
  files:
    ~/.npmrc: Dev/JavaScript/.npmrc
pip:
  files:
    ~/.config/pip/pip.conf: Dev/Python/pip.conf
conda:
  files:
    ~/.condarc: Dev/Python/.condarc
cargo:
  files:
    ~/.cargo/config: Dev/Rust/config
sbt:
  files:
    ~/.sbt/repositories: Dev/Scala/repositories
docker:
ansible:
hammerspoon:
  files:
    ~/.hammerspoon/init.lua: macOS/Hammerspoon/init.lua
sleepwatcher:
  files:
    ~/.sleep: macOS/SleepWatcher/.sleep
    ~/.wakeup: macOS/SleepWatcher/.wakeup
mac-mouse-fix:
  files:
    "~/Library/Application Support/com.nuebling.mac-mouse-fix/config.plist": macOS/Mac-Mouse-Fix/config.plist
obs: